### ISSUE TITLE
Unschöne Meldung bei MACHE

### ISSUE THREAD

**Issue by fantasya-pbem** [fantasya-pbem/host#18]
Das Maximum an Produktionskapazität wird falsch berechnet:

Einheit 5hy: Rüstungsbau 10, hat 122 Eisen
Befehl: MACHE Eisenschild
Meldung: Einheit [5hy] hat nicht genügend Eisen um 2147483647 Punkte bauen zu können, reduziert auf 24.

**Comment by fantasya-pbem** [comment]
Der Bug wurde wohl mit dem kürzlich eingeführten Feature "Multi-MACHE" eingeführt.

**Comment by palberla** [comment]
Wieviele Personen hat die Einheit und wieviele Eisenschilde wurden wirklich produziert? Sprich liegt ein Bug bei den Meldungen oder bei der wirklichen Berechnung vor?

**Comment by fantasya-pbem** [comment]
Bisher gab es keine Beschwerden über die Produktionszahlen. Ich halte es für einen Fehler in der Meldung.

**Comment by fantasya-pbem** [comment]
Die unschöne Meldung ist umformuliert zu "<Unit> hat ausreichend <Material>, um x Punkte bauen zu können.".

**Comment by fantasya-pbem** [comment]
Wir testen heute die Änderung in AW 478.
